//Auth_Actions
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

//Fetch_actions
export const FETCH_PANCARD_ALL_FAIL="FETCH_PANCARD_ALL_FAIL";
export const FETCH_PANCARD_ALL_SUCCESS="FETCH_PANCARD_ALL_SUCCESS";
export const FETCH_ALL_SORT_BY_FIXED_DEPO_FAIL="FETCH_ALL_SORT_BY_FIXED_DEPO_FAIL";
export const FETCH_ALL_SORT_BY_FIXED_DEPO_SUCCESS="FETCH_ALL_SORT_BY_FIXED_DEPO_SUCCESS";
export const FETCH_ONE_ID_FAIL="FETCH_ONE_ID_FAIL";
export const FETCH_ONE_ID_SUCCESS="FETCH_ONE_ID_SUCCESS";
export const FETCH_ALL_SORT_BY_Account_Type_FAIL="FETCH_ALL_SORT_BY_Account_Type_FAIL";
export const FETCH_ALL_SORT_BY_Account_Type_SUCCESS="FETCH_ALL_SORT_BY_Account_Type_SUCCESS";
export const FETCH_PANCARD_FLAGGED_ALL_FAIL="FETCH_PANCARD_FLAGGED_ALL_FAIL";
export const FETCH_PANCARD_FLAGGED_ALL_SUCCESS="FETCH_PANCARD_FLAGGED_ALL_SUCCESS";
//Fetch rquests


export const FETCH_PANCARD_ALL_REQUEST="FETCH_PANCARD_ALL_REQUEST";
export const FETCH_ALL_SORT_BY_FIXED_DEPO_REQUEST="FETCH_ALL_SORT_BY_FIXED_DEPO_REQUEST";
export const FETCH_ONE_ID_REQUEST="FETCH_ONE_ID_REQUEST";
export const FETCH_ALL_SORT_BY_Account_Type_REQUEST="FETCH_ALL_SORT_BY_Account_Type_REQUEST";
export const FETCH_PANCARD_FLAGGED_ALL_REQUEST="FETCH_PANCARD_FLAGGED_ALL_REQUEST";

//Patch - Flag account

export const FLAG_ID_ONE_REQUEST="FLAG_ID_ONE_REQUEST";
export const FLAG_ID_ONE_SUCCESS="FLAG_ID_ONE_SUCCESS";
export const FLAG_ID_ONE_FAIL="FLAG_ID_ONE_FAIL"
